Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
 Enabled: false

Style/ClassVars:
  Enabled: false

# Metrics/ClassLength:
#   Max: 220

Metrics/PerceivedComplexity:
  Max: 9

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 42

# Metrics/CyclomaticComplexity:
#   Max: 16

# Metrics/BlockLength:
#   Max: 35

# Layout/LineLength:
#   Max: 165